operators/knative-activator/src/charm.py
operators/knative-autoscaler/src/charm.py
operators/knative-controller/src/charm.py
operators/knative-controller/src/config.yaml.j2
operators/knative-eventing-controller/src/charm.py
operators/knative-eventing-webhook/src/charm.py
operators/knative-istio-controller/src/charm.py
operators/knative-istio-controller/src/config.yaml.j2
operators/knative-webhook/src/charm.py

Refactors ingress handling for istio network controller to use an existing ingress gateway rather than create its own.

Use common ingress gateway

---

.github/workflows/integrate.yaml
operators/knative-istio-controller/src/charm.py
operators/knative-istio-controller/tests/test_charm.py
tox.ini

Add leadership check and proper error handling in istio-controller
Fix unit tests for istio-controller
Added a unit test for no leadership
Add istio-controller to main tox file
Run lint and unit tests for istio-controller in CI

Add error handling and leadership check istio controller

---

.github/workflows/integration.yaml
.github/workflows/on_pull_request.yaml
.github/workflows/on_push.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml

.github/workflows: adds publish and release job

---

charms/knative-eventing/README.md
charms/knative-operator/README.md
charms/knative-serving/README.md

Adds missing README files for all Knative charms

Adds README at charm level

---

.github/workflows/integration.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml

ci: charming-actions version bump 1.0.3 -> 2.0.0-rc

---

README.md

Updates README with instructions to enable metrics collection.

docs: add instructions to enable metrics collection

---

.github/workflows/integration.yaml

ci: k8s version bump 1.2x -> 1.24

ci: k8s version bump 1.2x -> 1.24

---

charms/knative-serving/lib/charms/istio_pilot/v0/istio_gateway_info.py
charms/knative-serving/metadata.yaml
charms/knative-serving/src/charm.py
charms/knative-serving/tests/unit/test_charm.py

For sharing information to charms that depend on knative-serving local gateway information.

feat: share ingress and local gateway information using gateway-info

---

charms/knative-eventing/src/charm.py
charms/knative-serving/src/charm.py

refactor error handling
@DnPlas 
I feel that BlockedStatus is wrong here
should we refactor to generic charm error?

refactor errors

---

charms/knative-eventing/tox.ini
charms/knative-operator/tox.ini
charms/knative-serving/tox.ini
tox.ini

Updates tox.ini's `update-requirements` as described in https://github.com/canonical/argo-operators/pull/100

update tox.ini's update-requirements

---

.github/workflows/integrate.yaml
charms/knative-operator/requirements-integration.in
charms/knative-operator/requirements-integration.txt
requirements-integration.in
requirements-integration.txt

ci: update juju to 3.1 and microk8s to 1.25

ci: update juju to 3.1 and microk8s to 1.25

---

charms/knative-eventing/metadata.yaml
charms/knative-operator/metadata.yaml
charms/knative-serving/metadata.yaml

Links to docs for serving, eventing and operator.

Docs links

---

charms/knative-serving/config.yaml
charms/knative-serving/src/charm.py
charms/knative-serving/src/manifests/KnativeServing.yaml.j2
charms/knative-serving/tests/unit/test_charm.py
tests/test_bundle.py

feat: add config for queue sidecar image to `knative-serving` charm (#186)

---

charms/knative-eventing/requirements-unit.txt
charms/knative-eventing/requirements.txt
charms/knative-operator/requirements-integration.txt
charms/knative-operator/requirements-unit.txt
charms/knative-operator/requirements.txt
charms/knative-serving/requirements-unit.txt
charms/knative-serving/requirements.txt

Part of canonical/bundle-kubeflow#868

build: bump ops to latest possible version

---

charms/knative-eventing/requirements-unit.txt
charms/knative-eventing/requirements.txt
charms/knative-operator/requirements-unit.txt
charms/knative-operator/requirements.txt
charms/knative-serving/requirements-unit.txt
charms/knative-serving/requirements.txt

Part of canonical/bundle-kubeflow#883

build: bump jinja2 3.1.x -> 3.1.4

---

charms/knative-operator/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/knative-operator/requirements-integration.txt
charms/knative-operator/src/charm.py
charms/knative-operator/tests/integration/test_charm.py
charms/knative-operator/tests/unit/test_charm.py
requirements-integration.in
requirements-integration.txt
requirements-lint.txt
tests/test_cos_integration.py

Enable and add metrics from knative-operator itself.
Update also cos-integration tests.
How it can be tested:
```bash
$ tox -e cos-integration -- --keep-models
$ juju exec --model test-cos-integration-jz7i --unit grafana-agent-k8s/0 -- curl localhost:12345/agent/api/v1/metrics/targets | jq '.data.[] | select(.labels.juju_charm == "knative-operator")'
{
"instance": "4e26713916fe059c3703db8908760f03",
"target_group": "juju_test-cos-integration-jz7i_e313b562_knative-operator_prometheus_scrape",
"endpoint": "http://10.152.183.56:8889/metrics",
"state": "up",
"labels": {
"instance": "test-cos-integration-jz7i_e313b562-f2bb-4be3-89c6-fa201a3c5602_knative-operator",
"job": "juju_test-cos-integration-jz7i_e313b562_knative-operator_prometheus_scrape",
"juju_application": "knative-operator", …
```

Enable and add metrics from knative-operator

---

charms/knative-eventing/requirements-unit.txt
charms/knative-eventing/requirements.txt
charms/knative-operator/requirements-unit.txt
charms/knative-operator/requirements.txt
charms/knative-serving/requirements-unit.txt
charms/knative-serving/requirements.txt

Part of canonical/bundle-kubeflow#883

build: bump jinja2 3.1.x -> 3.1.4 (#206)

---

charms/knative-operator/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/knative-operator/requirements-integration.txt
charms/knative-operator/src/charm.py
charms/knative-operator/tests/integration/test_charm.py
charms/knative-operator/tests/unit/test_charm.py
requirements-integration.in
requirements-integration.txt
requirements-lint.txt
tests/test_cos_integration.py

Enable and add metrics from knative-operator itself. Update also cos-integration tests.

chore(backport): Add metrics from knative-operator (#212)

---

charms/knative-operator/config.yaml

Closes: https://github.com/canonical/knative-operators/issues/231 
We need to pin it as the latest bring some breaking ci change.

Pin otel controller image

---

charms/knative-operator/config.yaml

Closes: https://github.com/canonical/knative-operators/issues/231

Backport: Pin otel controller image (#232)

---

.github/workflows/integrate.yaml
charms/knative-eventing/charmcraft.yaml
charms/knative-operator/charmcraft.yaml
charms/knative-serving/charmcraft.yaml

Ref canonical/bundle-kubeflow#1178

build: Enable building rust dependencies

---

charms/knative-serving/src/charm.py
charms/knative-serving/tests/unit/test_charm.py

Integrate `net-istio-webhook` rock (#248)

---

.github/workflows/integrate.yaml
tests/test_bundle.py

Closes: https://github.com/canonical/knative-operators/issues/264
- Adds maximize space github action 
- Adds retry mechanism for http test
Tested on problematic PR: https://github.com/canonical/knative-operators/pull/259

Add maximise space action + add retry for http test

---

charms/knative-operator/lib/charms/loki_k8s/v1/loki_push_api.py
charms/knative-operator/lib/charms/observability_libs/v1/kubernetes_service_patch.py
charms/knative-operator/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
charms/knative-serving/lib/charms/istio_pilot/v0/istio_gateway_info.py

* Bump libraries using charmcraft fetch-lib.
* Check for major versions using noctua charm libraries check --major. If there is one, then commit a do-not-merge-message.txt file.
Ref canonical/bundle-kubeflow#1184

chore: bump libraries

---

.github/workflows/ci.yaml
.github/workflows/promote.yaml

chore: migrate GH runners to ubuntu 24.04

---

charms/knative-serving/src/default-custom-images.json

Closes: https://github.com/canonical/knative-operators/issues/311
Integrates all knative serving rcks which were missing. More details in the issue.

feat: integrate knative serving rocks

---

charms/knative-serving/src/default-custom-images.json

Closes: https://github.com/canonical/knative-operators/issues/311
Backports the changed images from main.

feat: integrate knative serving rocks (#313)

---

charms/knative-eventing/src/default-custom-images.json

Closes: https://github.com/canonical/knative-operators/issues/312
To test the mtping rock i have followed the instruction from this PR: https://github.com/canonical/knative-rocks/pull/34#pullrequestreview-2759781899

feat: integrate eventing rocks

---

charms/knative-eventing/src/default-custom-images.json

Backport of: https://github.com/canonical/knative-operators/pull/314

backport: eventing rocks

---

charms/knative-eventing/terraform/variables.tf
charms/knative-eventing/terraform/versions.tf
charms/knative-operator/terraform/variables.tf
charms/knative-operator/terraform/versions.tf
charms/knative-serving/terraform/variables.tf
charms/knative-serving/terraform/versions.tf

Cutting new release for branch track/1.16

[KF-7254] Release 1.10

---

charms/knative-eventing/terraform/variables.tf
charms/knative-operator/terraform/variables.tf
charms/knative-serving/terraform/variables.tf

[KF-7268] chore: pin channel to latest/edge

---

.github/workflows/ci.yaml
.github/workflows/tiobe_scan.yml
charms/knative-eventing/tox.ini
charms/knative-operator/tox.ini
charms/knative-serving/tox.ini
tox.ini

Updating with TIOBE scan, including:
* reformatting tox.ini file to be machine-generated and handled
* coverage.xml generation when running unit tests 
* creating tiobe_scan.yaml file

[KF-7281] Enabling TIOBE scan

---

tests/test_bundle.py

Pin charms-dependencies according to 1.10/stable bundle.
Close https://warthogs.atlassian.net/browse/KF-7233

chore(tests): Pin charms-dependencies
