- .github/workflows/integrate.yaml
Fixes issue where, on pushes to open pull requests, the integration CI runs twice (once for push (to the PR), and once for the PR update itself)
> fix: deduplicate integration ci

- charms/knative-eventing/charmcraft.yaml
- charms/knative-eventing/config.yaml
- charms/knative-eventing/metadata.yaml
- charms/knative-eventing/requirements.txt
- charms/knative-eventing/tox.ini
Makes changes on supporting files, adding configuration, metadata, requirements and other generics needed to build and operate.
This is built on top of #15
> knative-eventing: adapts supporting files to knative-eventing needs

- charms/knative-serving/charmcraft.yaml
- charms/knative-serving/config.yaml
- charms/knative-serving/metadata.yaml
- charms/knative-serving/requirements.txt
- charms/knative-serving/tox.ini
Makes changes on supporting files, adding configuration, metadata, requirements and other generics needed to build and operate.
This is built on top of #16
> knative-serving: adapts supporting files to knative-serving needs

- charms/knative-eventing/requirements.txt
- charms/knative-eventing/src/charm.py
- charms/knative-eventing/src/lightkube_custom_resources/operator.py
- charms/knative-eventing/src/manifests/KnativeEventing.yaml.j2
- charms/knative-eventing/src/manifests/Namespace.yaml.j2
- charms/knative-eventing/tests/unit/conftest.py
- charms/knative-eventing/tests/unit/test_charm.py
Initial implementation of knative-eventing, this PR includes changes in the charm code for handling Install and ConfigChanged events using [`charmed-kubeflow-chisme`](https://github.com/canonical/charmed-kubeflow-chisme). This PR also introduces unit tests for the charm.
This is built on top of #17
>  knative-eventing: initial implementation of the charm 

- charms/knative-serving/requirements.txt
- charms/knative-serving/src/charm.py
- charms/knative-serving/src/lightkube_custom_resources/operator.py
- charms/knative-serving/src/manifests/KnativeServing.yaml.j2
- charms/knative-serving/src/manifests/Namespace.yaml.j2
- charms/knative-serving/tests/unit/conftest.py
- charms/knative-serving/tests/unit/test_charm.py
Initial implementation of knative-eventing, this PR includes changes in the charm code for handling Install and ConfigChanged events using [`charmed-kubeflow-chisme`](https://github.com/canonical/charmed-kubeflow-chisme). This PR also introduces unit tests for the charm.
This is built on top of #18
>  knative-serving: initial implementation of the charm 

- charms/knative-serving/src/charm.py
- charms/knative-serving/src/manifests/KnativeServing.yaml.j2
This PR changes how errors are logged replacing `logger.info` with `logger.error`. It also corrects a variable name in the KnativeServing manifest.
> knative-serving: small fixes and chores

- README.md
Adds instructions in the root directory to deploy knative-operators. This README also includes a guide to deploy an integration example.
Partially fixes #27
> README.md: adds instructions for deploying knative-*

- .github/workflows/integration.yaml
- examples/cloudevents-player.yaml
- test-requirements.txt
- tests/test_bundle.py
Adds integration test case that deploys istio-operators and knative-operators, then runs a knative-serving and eventing [example](https://knative.dev/docs/getting-started/first-source/). 
This PR also introduces changes to the integration Github workflow to enable metallb in the testing environment.
Merge after #36 and #37
> Adds integration test cases for running serving-eventing example

- charms/knative-eventing/tox.ini
- charms/knative-operator/tox.ini
- charms/knative-serving/tox.ini
- test-requirements.txt
To avoid [errors](https://github.com/canonical/knative-operators/runs/7683678548?check_suite_focus=true#step:4:25) with breaking changes between v4.x and v5.x
> ci: pin flake8 to version 4.0.1 to avoid breaking changes with versions >= 5.x.x

- charms/knative-serving/src/manifests/KnativeServing.yaml.j2
The configuration of the local gateway was missing important keys,
like the gateway/istio namespace and the serving namespace. This
commit changes the configuration to avoid issues when sending/receiving
CloudEvents from different sources.
Fixes: canonical/knative-operators#40
Merge after #42
> fix: correct local-gateway configuration for knative-serving

- .github/workflows/integration.yaml
This is a temporary fix for https://bugs.launchpad.net/juju/+bug/1992833.
This should be fixed on release of juju 2.3.36 + libjuju 3.0.3
> feat: pin integration CI juju to 2.9.34

- .github/workflows/integration.yaml
- .github/workflows/publish.yaml
- .github/workflows/release.yaml
This patch uses charming-actions 2.1.1, which is compatible with charmcraft 2.1.0.  This will fix the CI publishing knative-operator.
> feat: bump charming-actions version

- README.md
Add missing channels for istio and knative, ensuring a correct deployment.
> docs: add istio and knative channels for deployment command

- .github/workflows/integration.yaml
- tests/test_bundle.py
- tests/test_cos_integration.py
- tox.ini
Github runners have limited resources, which may cause bottlenecks and even errors when running integration tests on demanding charms. Splitting the single integration test job into two prevent this from happening. The new jobs are:
* Integration
* Observability Integration
Merge before #62
> ci: split integration test in two due to limited resources

- charms/knative-eventing/requirements-integration.in
- charms/knative-operator/requirements-integration.in
- charms/knative-serving/requirements-integration.in
- requirements-integration.in
the juju agent 2.9.34 is not compatible with pythonlib-juju 3.1, causing the following error:
`juju.errors.JujuConnectionError: juju server-version 2.9.34 not supported`
To avoid this, we have to pin to a version below 3.1.
> tests: pin python-libjuju<3.1 to avoid unsupported version errors

- .github/workflows/integration.yaml
- charms/knative-eventing/src/charm.py
- charms/knative-eventing/src/lightkube_custom_resources/operator.py
- charms/knative-eventing/src/manifests/KnativeEventing.yaml.j2
- charms/knative-operator/metadata.yaml
- charms/knative-operator/requirements-integration.txt
- charms/knative-operator/requirements-unit.txt
- charms/knative-operator/requirements.in
- charms/knative-operator/requirements.txt
- charms/knative-operator/src/charm.py
- charms/knative-operator/src/manifests/auth_manifests.yaml.j2
- charms/knative-operator/src/manifests/config_manifests.yaml.j2
- charms/knative-operator/src/manifests/crds_manifests.yaml.j2
- charms/knative-operator/src/manifests/istio_ns.yaml.j2
- charms/knative-operator/src/manifests/secret_manifests.yaml.j2
- charms/knative-operator/src/manifests/webhook-service.yaml
- charms/knative-operator/tests/unit/test_charm.py
- charms/knative-serving/config.yaml
- charms/knative-serving/src/charm.py
- charms/knative-serving/src/manifests/KnativeServing.yaml.j2
- tests/test_bundle.py
- tests/test_cos_integration.py
This PR introduces the following:
* feat: knative-operator image version bump 1.1.0->1.8.1
* fix: remove istio ns
* feat: add webhook service and auth manifests
* feat: bump operator manifests 1.1.x -> 1.8.x
> 1.7 Release upgrades

- charms/knative-serving/lib/charms/istio_pilot/v0/istio_gateway_info.py
- charms/knative-serving/src/charm.py
- charms/knative-serving/tests/unit/test_charm.py
We want to send the gateway information on config changed also, not only on relation changed. This commit also removes the exception handling for when the relation does not exist.
Please note this PR should be merged after canonical/istio-operators#249, otherwise the unit tests will fail.
TODO:
> fix: send gateway info on config changed and remove exception

- tests/test_bundle.py
- tests/test_cos_integration.py
- tools/get-images.sh
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup. Script is specific for track/1.8 branch to capture all images for that branch. Branch is handled in kubeflow-ci and bundle automation using bundle file.
Summary of changes:
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.
> feat: updated get images script without branch checkout for track/1.8

- charms/knative-eventing/requirements-integration.in
- charms/knative-eventing/requirements-integration.txt
- charms/knative-eventing/requirements-unit.txt
- charms/knative-eventing/requirements.txt
- charms/knative-operator/requirements-integration.in
- charms/knative-operator/requirements-integration.txt
- charms/knative-operator/requirements-unit.txt
- charms/knative-operator/requirements.txt
- charms/knative-serving/requirements-integration.in
- charms/knative-serving/requirements-integration.txt
- charms/knative-serving/requirements-unit.txt
- charms/knative-serving/requirements.txt
- requirements-integration.in
- requirements-integration.txt
Bump these package versions to avoid the issues described in https://github.com/canonical/bundle-kubeflow/issues/648.
Part of canonical/bundle-kubeflow#648
> build: bump juju 2.9.44.0, pyyaml->6.0.1

- charms/knative-operator/metadata.yaml
- charms/knative-operator/src/manifests/auth_manifests.yaml.j2
- charms/knative-operator/src/manifests/config_manifests.yaml.j2
- charms/knative-operator/src/manifests/crds_manifests.yaml.j2
- charms/knative-operator/src/manifests/secret_manifests.yaml.j2
- charms/knative-operator/src/manifests/service_account.yaml.j2
- charms/knative-operator/src/manifests/webhook-service.yaml
- charms/knative-serving/config.yaml
Upgrade with the following versions:
- knative-operator to latest 1.10 being 1.10.3
- knative-serving to 1.10.2
- knative-eventing to 1.10.1
Kubeflow 1.8 Dependencies versions reference: kubeflow/manifests#2450
The minor versions for `knative-serving` and `knative-eventing` are to align with upstream: reference in PR kubeflow/manifests#2486
> 1.8 Upgrades to version 1.10.x

- tools/get-images.sh
There were some images that were not reported by get images script. They are not refernced in any part of this repository. Until a better solution for image retrieval is found, these images are placed into static list and will be reported by get images script.
Details are in: https://github.com/canonical/knative-operators/issues/137
Summary of changes:
- Added images to static list to be returned by get images script. Issue https://github.com/canonical/knative-operators/issues/137 has more context on the problem.
NOTE: This PR only applies to `track/1.8`
> fix: added missing images to static list on track/1.8

- charms/knative-eventing/config.yaml
- charms/knative-eventing/src/charm.py
- charms/knative-eventing/src/manifests/KnativeEventing.yaml.j2
- charms/knative-eventing/tests/unit/test_charm.py
Add config option to specify the component version, similar to what we do for knative-serving.
Closes #136
> knative-eventing: Add config option for component version

- .github/ISSUE_TEMPLATE/bug_report.yml
- tools/get-images.sh
Refer to this issue for more details: https://github.com/canonical/bundle-kubeflow/issues/679
Issue in this repo: https://github.com/canonical/knative-operators/issues/142
- Added script that produces list of container images managed by charms in this repository and/or by corresponding workloads. Image list is a combination of static and dynamic lists.
- Updated script to extract version and use it to download YAML files. Parse those files to extract images.
To extract KNative Serving images correctly the following 3 files from KNative repository will be parsed for images based on version in `./charms/knative-serving/config.yaml`. These files are located in `https://github.com/knative/serving/releases/download/knative-v<VERSION>/`
- `serving-core.yaml`
- `serving-hpa.yaml`
- …
> feat: get images on main

- .github/workflows/integrate.yaml
- charms/knative-serving/config.yaml
Revert knative-serving version to 1.8.0 since knative-operator cannot fetch manifests for versions >=1.10.x. More details in #147
1. Deploy `knative-operator`
2. Deploy `knative-serving` (from the PR's branch always)
3. Check that 
- there is no error or sth weird in `knativeserving` CR conditions (`kubectl get knativeserving -n knative-serving -o yaml`)
- it creates deployments that do not error out 
- it spins up pods for each of the deployments in `knative-serving` namespace that go in `Running` state
> knative-serving: Revert component's version to 1.8.0

- charms/knative-eventing/config.yaml
Bump the default version from 1.8.0 to 1.10.1
Fixes #144
> chore: bump knative-eventing 1.8.0 -> 1.10.1

- charms/knative-serving/config.yaml
> chore: bump serving 1.8.0 -> 1.10.2

- charms/knative-eventing/README.md
- charms/knative-eventing/config.yaml
- charms/knative-eventing/src/charm.py
- charms/knative-eventing/src/image_management.py
- charms/knative-eventing/src/manifests/KnativeEventing.yaml.j2
- charms/knative-eventing/tests/unit/test_charm.py
- charms/knative-eventing/tests/unit/test_image_management.py
- charms/knative-serving/README.md
- charms/knative-serving/config.yaml
- charms/knative-serving/src/charm.py
- charms/knative-serving/src/image_management.py
- charms/knative-serving/src/manifests/KnativeServing.yaml.j2
- charms/knative-serving/tests/unit/test_charm.py
- charms/knative-serving/tests/unit/test_image_management.py
- requirements-integration.in
- tests/test_bundle.py
- tools/get-images.sh
This PR cherry picks:
* a44a964
* ba30ceb
* a22dd6e
so knative-operators can be deployed in an airgap environment. 
These changes are mirroring in `track/1.8` what we currently have in `main`.
Fixes #159
> feat: make charms work on airgap environments

- charms/knative-operator/config.yaml
- charms/knative-operator/src/charm.py
- charms/knative-operator/src/manifests/observability/collector.yaml.j2
Pass the image to be used through a config option.
Fixes #161
> feat: make otel-collector image configurable

- tools/get-images.sh
Due to f3cc3e0, the get-images.sh script couldn't retrieve the otel-collector image. Changing the script to get the image name from config.yaml ensures it continues working.
> fix: fix image gathering for otel-collector-image

- .github/workflows/integrate.yaml
- charms/knative-eventing/config.yaml
- charms/knative-operator/metadata.yaml
- charms/knative-operator/src/manifests/auth_manifests.yaml.j2
- charms/knative-operator/src/manifests/crds_manifests.yaml.j2
- charms/knative-operator/src/manifests/secret_manifests.yaml.j2
- charms/knative-serving/config.yaml
- tests/test_bundle.py
closes: https://github.com/canonical/knative-operators/issues/181, https://github.com/canonical/knative-operators/issues/180, https://github.com/canonical/knative-operators/issues/179
Changes from https://github.com/knative/operator . Comparing tags `release-1.12` and `release-1.10` branches
Key changes: 
- image bumps 
- added new options to kourier object
> Change manifests for v1.12.3

- charms/knative-eventing/config.yaml
- charms/knative-serving/config.yaml
Adds missing images keys to `custom_images` config in `knative-serving` and `knative-eventing` charms
according to my findings in #185 
closes #185 
closes #150
> fix: add missing images to custom images default for serving and eventing

- charms/knative-operator/lib/charms/loki_k8s/v1/loki_push_api.py
- charms/knative-operator/metadata.yaml
- charms/knative-operator/requirements-integration.in
- charms/knative-operator/requirements-integration.txt
- charms/knative-operator/requirements-unit.txt
- charms/knative-operator/requirements.txt
- charms/knative-operator/src/charm.py
- charms/knative-operator/tests/integration/test_charm.py
- charms/knative-operator/tests/unit/test_charm.py
Added logging relation and cos integration tests from chisme.
fixes: #184
How I tested it:
from terminal
```bash
$ tox -e integration -- --model kubeflow --keep-models
$ juju consume u1-k8s:cos.loki-logging
Added u1-k8s:admin/cos.loki-logging as loki-logging
$ juju integrate loki-logging grafana-agent-k8s
$ charmcraft pack 
Created 'knative-operator_ubuntu-20.04-amd64.charm'.                                  
Charms packed:
knative-operator_ubuntu-20.04-amd64.charm
$ juju refresh knative-operator --path ./knative-operator_ubuntu-20.04-amd64.charm --force-units
$ kubectl logs -n kubeflow knative-operator-0 --container knative-operator-webhook | grep '\[knative-operator-webhook\]'
$ kubectl logs -n kubeflow knative-operator-0 --container knative-operator | grep '\[knative-operator\]'
```
I …
> Add logging relation knative-operator

- charms/knative-eventing/config.yaml
- charms/knative-operator/metadata.yaml
- charms/knative-operator/src/manifests/auth_manifests.yaml.j2
- charms/knative-operator/src/manifests/secret_manifests.yaml.j2
- charms/knative-serving/config.yaml
Closes #195 
This PR updates the manifest files of `knative-eventing`, `knative-serving`, `knative-operator`. No major changes were made.
> chore: update manifests

- .github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
> ci(upload-charm): use charmcraft from latest/candidate in track/1.12

- charms/knative-serving/config.yaml
- charms/knative-serving/src/charm.py
- charms/knative-serving/src/manifests/KnativeServing.yaml.j2
- charms/knative-serving/tests/unit/test_charm.py
- tests/test_bundle.py
backports #208 to `track/1.10`
1. Deploy the following bundle:
```
bundle: kubernetes
name: kubeflow
docs: https://discourse.charmhub.io/t/3749
applications:
istio-ingressgateway:
charm: istio-gateway
channel: 1.17/stable
scale: 1
trust: true
_github_repo_name: istio-operators
_github_repo_branch: track/1.17
options:
kind: ingress
istio-pilot:
charm: istio-pilot
channel: 1.17/stable
scale: 1
trust: true
_github_repo_name: istio-operators
_github_repo_branch: track/1.17
options:
default-gateway: kubeflow-gateway
knative-eventing:
charm: knative-eventing
channel: 1.10/stable
scale: 1
trust: true
options:
namespace: knative-eventing
_github_repo_name: knative-operators
_github_repo_branch: track/1.10
knative-operator:
charm: knative-operator
channel: 1.10/stable
scale: 1
trust: true …
```
> (cherry-pick to track/1.10) fix: configure proxy env vars in serving

- charms/knative-operator/src/prometheus_alert_rules/KubeflowKnativeOperatorServices.rules
- charms/knative-operator/tests/integration/test_charm.py
- tests/test_cos_integration.py
These alert rules provide an overview of all service states.
Using the KubeflowServiceDown or KubeflowServiceIsNotStable filter, the user
can easily see the status of all Kubeflow services.
These changes can be tested by running the following commands:
```bash
tox -e integration -- --keep-models
juju -m <model-name> show-unit grafana-agent-k8s/0 --endpoint metrics-endpoint | yq '.[]."relation-info".[]."application-data".alert_rules | fromjson'
juju consume <controller>:cos.remote-write
juju integrate remote-write grafana-agent-k8s
kubectl exec -it -n <model-name> pod/<pod-name> -c <workload-container> -- /charm/bin/pebble start <service-name>
```
part-of: [#1026](https://github.com/canonical/bundle-kubeflow/issues/1026)
> Add alert rules to knative-operator based on the KF093 spec

- charms/knative-serving/config.yaml
- charms/knative-serving/src/charm.py
- charms/knative-serving/src/manifests/KnativeServing.yaml.j2
- charms/knative-serving/tests/unit/test_charm.py
- tests/test_bundle.py
backports #208 to `track/1.12`
1. Deploy the following bundle:
```
bundle: kubernetes
name: kubeflow
docs: https://discourse.charmhub.io/t/3749
applications:
istio-ingressgateway:
charm: istio-gateway
channel: 1.22/stable
scale: 1
trust: true
_github_repo_name: istio-operators
_github_repo_branch: main
options:
kind: ingress
istio-pilot:
charm: istio-pilot
channel: 1.22/stable
scale: 1
trust: true
_github_repo_name: istio-operators
_github_repo_branch: main
options:
default-gateway: kubeflow-gateway
knative-operator:
charm: knative-operator
channel: 1.12/stable
scale: 1
trust: true
_github_repo_name: knative-operators
_github_repo_branch: main
knative-serving:
charm: knative-serving
channel: 1.12/stable
scale: 1
trust: true
options:
namespace: knative-serving
istio.gateway.namespace: …
```
> (cherry-pick to track/1.12) fix: configure proxy env vars in serving controller  (#208)

- .github/workflows/publish.yaml
Use charmcraft from latest/candidate in upload-charm in order to unify the channel used during integration tests and publishing.
Ref canonical/bundle-kubeflow#993
> ci(upload-charm): use charmcraft from latest/candidate in track/1.10

- CONTRIBUTING.md
- tools/get-images.sh
Closes https://github.com/canonical/knative-operators/issues/219
The PR hardcodes the version of net-istio to be used for the 1.12.4 version of Knative Service (used in CKF 1.9), similarly to how we handled it for CKF 1.8.
To verify:
```bash
./tools/get-images.sh | less
```
> scripts: Fix net-istio version for 1.9 scanning

- CONTRIBUTING.md
- tools/get-images.sh
This PR is a backport of #221 for `track/1.12`
It hardcodes the version of net-istio that is used for knative.
To test that it is actually working:
```
./tools/get-images.sh | less
```
> chore(backport-1.12) scripts: Fix net-istio version for 1.9 scanning 

- .github/workflows/integrate.yaml
- .gitignore
- charms/knative-eventing/terraform/README.md
- charms/knative-eventing/terraform/main.tf
- charms/knative-eventing/terraform/outputs.tf
- charms/knative-eventing/terraform/variables.tf
- charms/knative-eventing/terraform/versions.tf
- charms/knative-eventing/tox.ini
- charms/knative-operator/terraform/README.md
- charms/knative-operator/terraform/main.tf
- charms/knative-operator/terraform/outputs.tf
- charms/knative-operator/terraform/variables.tf
- charms/knative-operator/terraform/versions.tf
- charms/knative-operator/tox.ini
- charms/knative-serving/terraform/README.md
- charms/knative-serving/terraform/main.tf
- charms/knative-serving/terraform/outputs.tf
- charms/knative-serving/terraform/variables.tf
- charms/knative-serving/terraform/versions.tf
- charms/knative-serving/tox.ini
Create a `terraform/` directory for each of the charms to host their individual Terraform modules. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is based on what was done in canonical/argo-operators#198.
To test the modules:
- Clone the repository and switch this PR's branch.
- For each charm:
- `cd` into its directory 
- First run `tox -e tflint` to ensure that linting is correct
- Create a juju controller and a model name `kubeflow`
- Run `terraform apply -var "channel=latest/edge" -var "model_name=kubeflow" --auto-approve` and wait until the charm is `Active` and `Idle`. Note that eventing and serving won't go to active because of #156.
This should be merged after …
> feat: Add terraform modules for knative-{eventing,operator,serving}

- .github/workflows/integrate.yaml
- .gitignore
- charms/knative-eventing/terraform/README.md
- charms/knative-eventing/terraform/main.tf
- charms/knative-eventing/terraform/outputs.tf
- charms/knative-eventing/terraform/variables.tf
- charms/knative-eventing/terraform/versions.tf
- charms/knative-eventing/tox.ini
- charms/knative-operator/terraform/README.md
- charms/knative-operator/terraform/main.tf
- charms/knative-operator/terraform/outputs.tf
- charms/knative-operator/terraform/variables.tf
- charms/knative-operator/terraform/versions.tf
- charms/knative-operator/tox.ini
- charms/knative-serving/terraform/README.md
- charms/knative-serving/terraform/main.tf
- charms/knative-serving/terraform/outputs.tf
- charms/knative-serving/terraform/variables.tf
- charms/knative-serving/terraform/versions.tf
- charms/knative-serving/tox.ini
Create a `terraform/` directory for each of the charms to host their individual Terraform modules. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is based on what was done in canonical/argo-operators#198.
Closes #224 
Closes #225 
Closes #226
> feat: Backport terraform modules for knative-{eventing,operator,serving} from #227

- charms/knative-operator/src/prometheus_alert_rules/KubeflowKnativeOperatorServices.rules
- charms/knative-operator/tests/integration/test_charm.py
- tests/test_cos_integration.py
Part of: https://github.com/canonical/bundle-kubeflow/issues/1109
* Add alert rules to knative-operator based on the KF093 spec
* add cos integration tests for alert rules
> Backport: Add alert rules to knative-operator based on the KF093 spec (#215)

- charms/knative-operator/metadata.yaml
Closes https://github.com/canonical/knative-operators/issues/245
Integrates the `knative-operator` Rock built from [this On Push CI run](https://github.com/canonical/knative-rocks/actions/runs/11929145009/job/33247869792), introduced in PR https://github.com/canonical/knative-rocks/pull/6.
> feat: integrate `knative-operator` rock

- charms/knative-operator/metadata.yaml
Closes #244 
Integrates the `knative-operator-webhook-image` resource in the `knative-operator` charm to use the rock published from [this Push job](https://github.com/canonical/knative-rocks/actions/runs/12064975175/job/33643304750).
> feat: integrate operator `webhook` rock

- charms/knative-serving/config.yaml
- charms/knative-serving/src/charm.py
- charms/knative-serving/tests/unit/test_charm.py
Closes: https://github.com/canonical/knative-operators/issues/241
As described in the issue we decided to change the value in `DEFAULT_IMAGES` for now.
If you want to run a simple manual test to be 100% sure everything is ok you can run bundle integration tests locally and then check the pods in serving namesapce: 
```
tox -e integration -- --model kubeflow --keep-models -vv -s
kubectl get po -n knative-serving
NAME                                                     READY   STATUS      RESTARTS   AGE
activator-76db578547-dpbfd                               1/1     Running     0          12s
autoscaler-57c4f8d4dd-zclxf                              1/1     Running     0          12s
autoscaler-hpa-d9f489c5f-tb9lg                           1/1     Running     0          10s …
```
> Integrate `net-istio-webhook` rock

- tests/test_bundle.py
Closes: https://github.com/canonical/knative-operators/issues/253
Added retry mechanism for custom image test
I have ran the test locally few times and 5 times in ci
> Add retry for custom image test

- charms/knative-operator/config.yaml
- charms/knative-operator/src/manifests/observability/collector.yaml.j2
Update otel-collector to use version 0.117.0. Due to deprecation of `logging` configuration, update collector.yaml.j2 according to upstream instruction in open-telemetry/opentelemetry-collector#11337
Fix #235 
Observability tests should pass. For manual testing:
```bash
juju deploy knative-operator --channel latest/edge/pr-274 --trust --base ubuntu@20.04
juju deploy knative-eventing --channel latest/edge/pr-274 --trust --base ubuntu@20.04 --config namespace="knative-eventing"
juju deploy knative-serving --channel latest/edge/pr-274 --trust --base ubuntu@20.04 --config namespace="knative-serving" --config istio.gateway.namespace="kubeflow" --config istio.gateway.name="kubeflow-gateway"
juju deploy prometheus-k8s --trust --channel latest/stable
juju relate prometheus-k8s:metrics-endpoint …
```
> chore: bump otel-collector to 0.117.0

- charms/knative-eventing/src/charm.py
- charms/knative-eventing/tests/unit/test_charm.py
- charms/knative-serving/src/charm.py
- charms/knative-serving/tests/unit/test_charm.py
The Knative Serving and Eventing charms have a strong dependency on knative-operator, as it is the application that applies the KnativeServing and KnativeEventing CRDs and has the business logic to reconcile such CRs. Because the Knative Serving and Eventing charms depend entirely on the existence of those CRDs, this commit refactors the charms logic to:
1. Use a main event handler that can be deferred in case the required CRDs are not present
2. Remove any operation for the on_install event, and use the main event handler for config_changed as it is guaranteed that it'll be triggered right after on_install
Fixes #156
1. Deploy knative-{serving|eventing}
2. Depending on which charm, you may need to run some configs, for example, for serving:
```
juju config knative-serving …
```
> refactor: use main event handler and defer it if Knative CRDs are not found

- charms/knative-eventing/src/charm.py
In a previous commit, a check for knative CRDs was introduced, but for knative-eventing, it was incorrectly set up. This commit fixes the name of the CRD that the knative-eventing charm should look up for.
> fix: fix the name of CRD that knative-eventing looks for

- charms/knative-eventing/src/charm.py
- charms/knative-eventing/tests/unit/test_charm.py
- charms/knative-serving/src/charm.py
- charms/knative-serving/tests/unit/test_charm.py
* refactor: use main event handler and defer it if Knative CRDs are not found
The Knative Serving and Eventing charms have a strong dependency on knative-operator, as it is the application that applies the KnativeServing and KnativeEventing CRDs and has the business logic to reconcile such CRs. Because the Knative Serving and Eventing charms depend entirely on the existence of those CRDs, this commit refactors the charms logic to:
1. Use a main event handler that can be deferred in case the required CRDs are not present
2. Remove any operation for the on_install event, and use the main event handler for config_changed as it is guaranteed that it'll be triggered right after on_install
Part of #156
Fixes #279
> refactor: use main event handler and defer it if Knative CRDs are not found (#276)

- .github/workflows/integrate.yaml
- .github/workflows/publish.yaml
- charms/knative-eventing/charmcraft.yaml
- charms/knative-operator/charmcraft.yaml
- charms/knative-serving/charmcraft.yaml
Refactor charmcraft.yaml files to enable the usage of charmcraft-cache and data-platform-workflows in general. See issue for details
Close #271
Note that:
* this points to a dev branch as there is still pending work for #272 #277
* It is expected to be merged in red due to parallel builds being problematic with charmcraft 3.3. This will be fixed in the pending work linked above.
> build: refactor charmcraft.yaml to use ST124 notation

- .github/workflows/ci.yaml
`integration-charm-deployment` and `integration-charm-deployment` were running the [bundle integration tests](https://github.com/canonical/knative-operators/tree/main/tests). Merge those into one called `bundle-integration` for clarity in order to remove duplicate code and run both `cos-integration` and vanilla `integration` environment using a matrix.
A follow-up PR will enable charm integration tests also (see https://github.com/canonical/knative-operators/issues/288)
> refactor(ci): Remove duplicate code by merging integration environments

- .github/workflows/ci.yaml
- tox.ini
Run charm integration tests in CI workflows.
Fix #288
> fix(ci): Run charm integration tests in CI

- charms/knative-operator/metadata.yaml
Closes https://warthogs.atlassian.net/browse/KF-6945
Integrates the rock into `knative-operator-image` resource published by [this on push](https://github.com/canonical/knative-rocks/actions/runs/13264306275/job/37028660962)
> chore: integrate operator rock v1.16

- charms/knative-operator/metadata.yaml
Closes https://warthogs.atlassian.net/browse/KF-6946
Integrates the rock into `knative-operator-webhook-image` resource published by [this on push](https://github.com/canonical/knative-rocks/actions/runs/13178247512/job/36783281211)
> chore: integrate webhook rock v1.16

- charms/knative-serving/src/charm.py
Integrate net-istio-webhook:1.16.0-4214206 rock in preparation for a new release.
This component is not necessarily tested directly in the CI, but to make sure it works:
1. Deploy the knative-operator and knative-serving, their charm dependencies, and configure them properly (refer to the README.md in the root of this repo)
2. Wait for the knative-serving charm to go active and idle
3. In the `knative-serving` namespace, there should be a number of Pods with various names, we are interested in the `net-istio-webhook-***-***`
4. Verify that the Pod is in a `Running` state
5. Verify the service is running as expected by checking the logs of the Pod. It should be just showing info messages like:
```
2024-11-28T13:03:06.549Z [net-istio-webhook] …
```
> chore: integrate net-istio-webhook:1.16.0-4214206 rock

- charms/knative-serving/src/charm.py
Integrate net-istio-controller and migrate rocks for 1.16
Close https://warthogs.atlassian.net/browse/KF-6988
Close https://warthogs.atlassian.net/browse/KF-6989
1, Follow instructions from #300 and then
1. Check pods `net-istio-controller-xxxx-xxx` and `storage-version-migration-serving-serving-1.16.0-xxxx` that are in `Running` state.
2. `kubectl exec` into the pods and check logs using `pebble logs` for errors. In my case, [logs from net-istio-controller](https://pastebin.canonical.com/p/dQTXZPDVpc/) and [logs from migrate pod](https://pastebin.canonical.com/p/KDFbXkJs9d/)
> chore: integrate net-istio-controller and migrate rocks

- charms/knative-operator/config.yaml
- charms/knative-operator/src/manifests/observability/collector.yaml.j2
Closes https://warthogs.atlassian.net/browse/KF-7057
* Integrates [otel collector rock](https://github.com/canonical/opentelemetry-collector-rock) by o11y team to `knative-operator` charm
* Bumps otel collector image from `0.117.0` to `0.120.0`
* Modifies the otel collector deployment yaml to pass the config argument to the pebble service. Note that this is needed due to the `entrypoint-service` not being set in the rock. See the change in https://github.com/canonical/opentelemetry-collector-rock/pull/10. Without passing `--args <pebble service name>` before the config arg, we'd get the error `error: unknown flag config`.
Observability tests should pass. For manual testing:
```
juju deploy knative-operator --channel latest/edge/pr-303 --trust --base ubuntu@20.04
juju deploy …
```
> chore: integrate opentelemetry-collector rock

- CONTRIBUTING.md
Removes notice on images script limitation in CONTRIBUTING.md due to it being fixed in #304 
Note that the linked issue #220  was also closed
> docs: remove images script notice from CONTRIBUTING.md

- .github/workflows/ci.yaml
- charms/knative-eventing/charmcraft.yaml
- charms/knative-eventing/constraints.txt
- charms/knative-operator/charmcraft.yaml
- charms/knative-operator/constraints.txt
- charms/knative-serving/charmcraft.yaml
- charms/knative-serving/constraints.txt
Due to python/importlib_metadata#516, we need to set up constaints
to the `setuptools-scm` to avoid install loops for these charms dependencies,
as recommended by the charmcraft team (see https://github.com/canonical/charmcraft/issues/2259#issuecomment-2842766428).
Fixes #320
> fix(workaround): set constraints to setuptools-scm to avoid install loops

- charms/knative-eventing/charmcraft.yaml
- charms/knative-eventing/constraints.txt
- charms/knative-operator/charmcraft.yaml
- charms/knative-operator/constraints.txt
- charms/knative-serving/charmcraft.yaml
- charms/knative-serving/constraints.txt
Due to python/importlib_metadata#516, we need to set up constaints to the `setuptools-scm` to avoid install loops for these charms dependencies, as recommended by the charmcraft team (see https://github.com/canonical/charmcraft/issues/2259#issuecomment-2842766428).
Fixes #320
> cherry-pick: setuptools-scm fix (only one commit) from #323

- charms/knative-eventing/config.yaml
- charms/knative-eventing/src/default-custom-images.json
Ref: #327
This PR adds the `job-sink/job-sink` image to the default images in `default-custom-images.json`. This means that users can potentially change the default image deployed by replacing the image with the one they want
To test:
- Deploy the 3 knative charms (with trust)
- Replace the value of the `job-sink` key in `default-custom-images.json` with a different image, for example: `gcr.io/knative-releases/knative.dev/eventing/cmd/jobsink@sha256:3e5270924afeeccc8dfe31142a1c7f7e3ec3489df11b4c81f69f352a788ad207`. A
- Refresh the charm with `juju refresh knative-eventing --channel=latest/edge/pr-328` 
- Describe the respective deployment with `kubectl describe deploy -n knative-eventing job-sink`
- You should see the new image in the `job-sink` container.
This is needed for the rock …
> feat: Add `job-sink` key to `default-custom-images.json`

- .github/workflows/ci.yaml
- charms/knative-eventing/constraints.txt
- charms/knative-eventing/src/default-custom-images.json
Closes #327 
This PR replaces the upstream image for `job-sink` with the rock published in [the following action](https://github.com/canonical/knative-rocks/actions/runs/15205511310/job/42767604549).
Note that we're also re-enabling `cache` in the CI which will use the cached charms from `charmcraftcache-hub`.
First, refresh the `knative-eventing` charm with the proper channel:
```
juju refresh knative-eventing --channel=latest/edge/pr-330
```
Then I followed the [integration example](https://github.com/canonical/knative-operators?tab=readme-ov-file#integration-example) in the `README.md` to create a service and tried to curl it with the appropriate headers. I got the same results using both the upstream image and the rock:
```
curl -i …
```
> feat: Integrate job-sink rock
